# Generated by Django 3.2.3 on 2022-10-04 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('fieldid', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(help_text='輸入論文相關領域', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('methodologyid', models.AutoField(primary_key=True, serialize=False)),
                ('methodology', models.CharField(help_text='輸入論文有應用到的方法', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('ownerid', models.IntegerField(help_text='輸入工號', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='輸入中文名', max_length=100)),
                ('location', models.CharField(help_text='輸入廠區代號', max_length=100)),
                ('deptname', models.CharField(help_text='輸入中文部門', max_length=100)),
                ('deptno', models.CharField(help_text='輸入部門代號', max_length=100)),
                ('email', models.EmailField(help_text='輸入公司信箱', max_length=100)),
                ('tel', models.CharField(help_text='輸入桌機電話號碼', max_length=100)),
                ('account', models.CharField(help_text='輸入NT帳號', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paperid', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(help_text='輸入論文年份', max_length=4)),
                ('title', models.TextField(help_text='輸入論文標題')),
                ('author', models.CharField(help_text='輸入論文第一作者', max_length=20)),
                ('periodical', models.CharField(help_text='輸入論文的刊登期刊', max_length=20)),
                ('conditions', models.TextField(help_text='輸入論文方法的使用條件')),
                ('abstract', models.TextField(help_text='輸入論文摘要')),
                ('conclusions', models.TextField(help_text='輸入論文結論')),
                ('advantages', models.TextField(help_text='輸入論文方法的優點')),
                ('disadvantages', models.TextField(help_text='輸入論文方法的缺點')),
                ('keywords', models.TextField(help_text='輸入論文英文關鍵字', null=True)),
                ('paperlink', models.TextField(help_text='輸入論文pdf檔案連結')),
                ('githublink', models.TextField(help_text='輸入論文pdf檔案連結', null=True)),
                ('method', models.TextField(help_text='輸入論文使用的方法')),
                ('hitcount', models.IntegerField(help_text='輸入論文的點擊次數', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectid', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(help_text='輸入論文有應用到的專案', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MLTDC_Join_Table',
            fields=[
                ('mltdcid', models.AutoField(primary_key=True, serialize=False)),
                ('createtime', models.DateField(help_text='輸入登打日期')),
                ('field', models.ForeignKey(db_column='fieldid', on_delete=django.db.models.deletion.CASCADE, to='mltdc.field')),
                ('methodology', models.ForeignKey(db_column='methodologyid', on_delete=django.db.models.deletion.CASCADE, to='mltdc.methodology')),
                ('owner', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.CASCADE, to='mltdc.owner')),
                ('paper', models.ForeignKey(db_column='paperid', on_delete=django.db.models.deletion.CASCADE, to='mltdc.paper')),
            ],
            options={
                'db_table': 'mltdc_join_table',
            },
        ),
        migrations.CreateModel(
            name='Implement_Join_Table',
            fields=[
                ('implementid', models.AutoField(primary_key=True, serialize=False)),
                ('implementdate', models.DateField(help_text='輸入開始實作的日期')),
                ('result', models.TextField(help_text='輸入你實作的結果')),
                ('runtime', models.FloatField(help_text='輸入你運行的時間(hr)')),
                ('datasource', models.TextField(help_text='輸入你實作的資料與程式碼連結')),
                ('note', models.TextField(help_text='輸入任何補充事項', null=True)),
                ('createtime', models.DateField(help_text='輸入登打日期')),
                ('field', models.ForeignKey(db_column='fieldid', on_delete=django.db.models.deletion.CASCADE, to='mltdc.field')),
                ('owner', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.CASCADE, to='mltdc.owner')),
                ('paper', models.ForeignKey(db_column='paperid', on_delete=django.db.models.deletion.CASCADE, to='mltdc.paper')),
                ('project', models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, to='mltdc.project')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('starid', models.AutoField(primary_key=True, serialize=False)),
                ('star', models.IntegerField(help_text='輸入開始實作的日期')),
                ('owner', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.CASCADE, to='mltdc.owner')),
                ('paper', models.ForeignKey(db_column='paperid', on_delete=django.db.models.deletion.CASCADE, to='mltdc.paper')),
            ],
        ),
    ]
